/*assign01_task05- Sales Prediction*/

#include <iostream>
using namespace std;
int main()
{
    int totalSalesAmount = 680;
    int spDevisionSale = 62; // The South Punjab sales division in percentage, so it neends to be changed
    double predictedAmount;

    predictedAmount = (totalSalesAmount * spDevisionSale) / 100;

    cout << "The predicted amount is " << predictedAmount << " which is generated by South Punjab Devision on the base of 62%, of total sales." << endl;

    return 0;
}